### ISSUE TITLE
srs account for sample size difference?

### ISSUE THREAD

**Issue by marwa38** [vitorheidrich/SRS#2]
Do you think that the SRS helps in accounting for the variance difference because of the sample size difference (n=36 vs n=6)? So when using Mann Whitney later, the difference in variance won't be a problem?

Cheers
M

**Comment by vitorheidrich** [comment]
Hi @marwa38, sorry for the delayed response. No, SRS won't help dealing with the different sample sizes between study groups. However, SRS can be used to account for differential sequencing effort across different samples. In this sense, your groups will be more comparable from the sequencing effort point of view after normalizing your dataset using SRS, but that's all, you will likely be underpowered in any case for Mann-Whitney with such low numbers in one of the groups.
